import Navigation from '@/components/Navigation'
import './globals.css'

export const metadata = {
  title: 'My first next app',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="https://bootswatch.com/5/solar/bootstrap.min.css" />
      </head>
      <body>
        <Navigation />
        <div className='container p4'>{children}</div>
      </body>
    </html>
  )
}
